name: Build Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build job-runner container image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          target: runtime-job-runner
          tags: |
            ghcr.io/strayer/game-server-deployment-discord-bot/job-runner:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build discord-bot container image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          target: runtime-discord-bot
          tags: |
            ghcr.io/strayer/game-server-deployment-discord-bot/discord-bot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build server-launch-watcher container image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          target: runtime-server-launch-watcher
          tags: |
            ghcr.io/strayer/game-server-deployment-discord-bot/server-launch-watcher:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build valheim container image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          target: valheim
          file: Dockerfile.steamcmd
          tags: |
            ghcr.io/strayer/game-server-deployment-discord-bot/valheim:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build backup container image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: Dockerfile.backup
          tags: |
            ghcr.io/strayer/game-server-deployment-discord-bot/backup:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
